touchscreen: gt1151q: Don't use clang's builtin defs for fwrite
We have it defined in the driver itself. Using clang's defs leads to errors like:

drivers/built-in.o: In function `_save_testing_data':
kernel_xiaomi_onc/drivers/input/touchscreen/gt1151q/test_function.c:1077: undefined reference to `fwrite_unlocked'
kernel_xiaomi_onc/drivers/input/touchscreen/gt1151q/test_function.c:1099: undefined reference to `fwrite_unlocked'
kernel_xiaomi_onc/drivers/input/touchscreen/gt1151q/test_function.c:951: undefined reference to `fwrite_unlocked'
kernel_xiaomi_onc/drivers/input/touchscreen/gt1151q/test_function.c:965: undefined reference to `fwrite_unlocked'
kernel_xiaomi_onc/drivers/input/touchscreen/gt1151q/test_function.c:1116: undefined reference to `fwrite_unlocked'
drivers/built-in.o:kernel_xiaomi_onc/drivers/input/touchscreen/gt1151q/test_function.c:1125: more undefined references to `fwrite_unlocked' follow

- Required after: https://github.com/llvm-mirror/clang/commit/0504bf2ebb0949b0d304829406dcbe7793d0d42f

Change-Id: I61498d2f14afb194df723c3fea31aee4a572b6ed
Signed-off-by: theimpulson <aayushgupta219@gmail.com>